
const state = {
  page: "manager",
  loading: true,
  settings: null,
  openaiScriptExamples: {
    text_to_image: "",
    image_to_image: "",
  },
  openaiGoogleScriptExamples: {
    text_to_image: "",
    image_to_image: "",
  },
  sysrvGoogleScriptExamples: {
    text_to_image: "",
    image_to_image: "",
  },
  apimartOpenAIScriptExamples: {
    text_to_image: "",
    image_to_image: "",
  },
  settingsProviderDraftIsNew: false,
  settingsEditingProvider: "",
  settingsDirty: false,
  isComposingPrompt: false,
  saveViewMode: "list",
  saveAreaKeyboardFocus: false,
  hoverPreview: {
    path: "",
  },
  settingsCodeExample: {
    tab: "fixed-example",
    customTabExplicit: false,
    editing: true,
    editDraft: "",
    customEditOrigin: "",
  },
  generationStatus: {
    inProgress: false,
    message: "",
    type: "info",
    startedAt: "",
    error: "",
  },
  generationTasks: [],
  pendingInstances: [],
  pendingStartedAtByKey: new Map(),
  pendingTimerId: 0,
  runningRefreshTimerId: 0,
  runningRefreshInFlight: false,
  runningRefreshNeedsRender: false,
  managerInteractionUntil: 0,
  savePageNavigationUntil: 0,
  instanceListRequestSeq: 0,
  cancellingGenerationTaskIds: new Set(),
  clipboardImageTarget: null,
  operation: {
    generation_path: "",
  },
  providerMarkers: {},
  filters: {
    q: "",
    tags: [],
    tag_search: "",
    tag_dropdown_open: false,
    source: "all",
    mode_filter: "all",
    provider: "all",
    status: "all",
    statuses: [],
    status_dropdown_open: false,
    size: "all",
    call_method: "all",
    model: "all",
    start_date: "",
    end_date: "",
    sort: "created_desc",
    page: 1,
    per_page: 50,
    filterOptions: {
      providers: [],
      sizes: [],
      call_methods: [],
      models: [],
      statuses: [],
    },
  },
  instances: [],
  selectedInstanceIds: new Set(),
  lastSelectedInstanceId: "",
  tagOptions: [],
  nodes: [],
  nodeMenu: {
    openKey: "",
  },
  nodeContextMenu: {
    open: false,
    node_id: null,
    x: 0,
    y: 0,
  },
  nodeDrag: {
    active: false,
    node_id: null,
    parent_id: null,
    suppressClick: false,
  },
  tagManagementContextMenu: {
    open: false,
    tag_id: null,
    tag_name: "",
    x: 0,
    y: 0,
  },
  generationPathHistory: [],
  successfulProviderFieldHistory: {
    api_key_env: [],
    model: [],
    user_agent: [],
  },
  settingsSharedProviderFieldHistory: {
    api_key_env: [],
    model: [],
    user_agent: [],
  },
  generationPathDropdownOpen: false,
  settingHistoryDropdownOpen: "",
  nodeFilter: {
    path: [{ selection: "all", node_id: null }],
  },
  total: 0,
  history: {
    items: [],
    total: 0,
    page: 1,
    per_page: 50,
    q: "",
    tags: [],
    tag_search: "",
    history_tag_dropdown_open: false,
    status: "all",
    provider: "all",
    size: "all",
    mode: "all",
    call_method: "all",
    model: "all",
    number_type: "all",
    start_date: "",
    end_date: "",
    filterOptions: {
      providers: [],
      sizes: [],
      modes: [],
      call_methods: [],
      models: [],
      statuses: [],
      tags: [],
    },
    cleanup: {
      running: false,
      before_date: "",
    },
    loading: false,
    error: "",
  },
  dataSafety: {
    backups: [],
    loading: false,
    error: "",
    status: "",
    selectedBackupPath: "",
    exportTaskId: "",
    exportTask: null,
    restorePreview: null,
    backingUp: false,
    exporting: false,
    restoring: false,
    clearingThumbnails: false,
    thumbnailCache: {
      file_count: 0,
      size_label: "0 B",
      path: "",
    },
  },
  tagManagement: {
    items: [],
    total: 0,
    q: "",
    loading: false,
    error: "",
    status: "",
    mergeDialog: {
      open: false,
      targetId: "",
    },
  },
  editing: new Map(),
  savingInstances: new Set(),
  undoStack: [],
  redoStack: [],
  lightbox: {
    path: "",
    gallery: [],
    galleryIndex: 0,
    zoom: 1,
    error: "",
    panX: 0,
    panY: 0,
    isDragging: false,
    dragStartX: 0,
    dragStartY: 0,
    dragOriginX: 0,
    dragOriginY: 0,
  },
};

const LIGHTBOX_MIN_ZOOM = 0.25;
const LIGHTBOX_MAX_ZOOM = 5;
const LIGHTBOX_ZOOM_STEP = 0.25;

const OPERATION_DEFAULTS = {
  mode: "text_to_image",
  prompt: "",
  input_image_paths: [],
  tags: [],
  generation_path: "",
  provider_dropdown_open: false,
  aspect_ratio: "1:1",
  generation_size: DEFAULT_GENERATION_SIZE,
  generation_clarity: DEFAULT_GENERATION_RESOLUTION,
  resolution: DEFAULT_GENERATION_RESOLUTION,
  custom_resolution: "",
  generation_count: 1,
  text_generation_count: 1,
  aspect_ratio_picker_open: false,
  clarity_picker_open: false,
  size_picker_open: false,
  resolution_picker_open: false,
  custom_generation_size: "",
  size_error: "",
  tag_draft: "",
  tag_selector_open: false,
};


Object.assign(globalThis, {
  state,
  LIGHTBOX_MIN_ZOOM,
  LIGHTBOX_MAX_ZOOM,
  LIGHTBOX_ZOOM_STEP,
  OPERATION_DEFAULTS,
});
